version: "3"
services:
  db:
    image: postgres:13.3
    volumes:
      - ~/docker/volumes/nanosplit_development:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    container_name: nanosplit-postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
  redis:
    image: redis
    ports:
      - "6379:6379"
