default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: nanosplit_development
  
test:
  <<: *default
  database: nanosplit_test

production:
  <<: *default
  database: nanosplit_production
  username: nanosplit
  password: <%= ENV['NANOSPLIT_DATABASE_PASSWORD'] %>
